name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * 1"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: pacman

      - name: Prepare deploy directory
        run: |
          mkdir -p deploy

          cp dist/pacman-contribution-graph.svg deploy/pacman-contribution-graph.svg
          
          cp dist/pacman-contribution-graph.svg deploy/pacman-contribution-graph-dark.svg

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pacman-output
          publish_dir: ./deploy
          force_orphan: true
