name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 1/23 1 * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: pacman

      - name: Show generated files
        run: find . -type f

      - name: Debug workspace
        run: |
          pwd
          ls -lah
          file dist || true
          find . -maxdepth 2

      - name: Prepare deploy folder
        run: |
            rm -rf deploy
            mkdir -p deploy
        
            find . -name "*.svg" -exec cp {} deploy/ \;
        
            ls -R deploy

      - name: Deploy to pacman-output
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pacman-output
          publish_dir: ./deploy
          force_orphan: true
