name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 1/23 1 * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: pacman

      - name: Show generated files
        run: find . -type f

      - name: Prepare deploy folder
        run: |
          mkdir dist

          find . -name "*.svg" -exec cp {} dist/ \;

          ls -R dist

      - name: Deploy to pacman-output
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pacman-output
          publish_dir: ./dist
          force_orphan: true
